eureka:
  client:
    servive-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8000
spring:
  application:
    name: currency-exchange-service
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
