eureka:
  client:
    servive-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8100
spring:
  application:
    name: currency-conversion-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
